### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by ReshyResh** [lily-coder/myportfolio#12]
Hi, Lilian! Your code looks great and there are no big issues that need addressing, just a few suggestions! 🎉

# Suggestions ♻️

- The content of the webpage in your template is supposed to be always centered, no matter the width of the screen. Yours is sticking to the left side of the screen, kindly work on that! 

**This is what it should look like**
![](https://i.imgur.com/xSXGjgi.png)

- You're using .svg files for the background shapes in the portfolio, but you don't need them as they're made using pure CSS as shown in the template's code. Kindly remove the images to avoid wasting device memory! 
**Here's a difference between your code and the template's: [Line 262 in style.css](https://github.com/lily-coder/myportfolio/blob/main/style.css#L262)**

![](https://i.imgur.com/vgmrynl.png)

![](https://i.imgur.com/tNzgLfV.png)

- Add a bit more padding to the contact section to strongly mark it as another section, the way it is now looks like it's a continuation of the previous section. 

**Other than that you have a very well-structured code, good job!**

# Cheers and happy coding! 🚀

**Comment by lily-coder** [comment]
Thank you so much.
I have centered the content of my webpage
I have removed the background images from the css ellipses
I have added more padding to the contact section
